# Generated by Django 2.1.3 on 2019-01-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('pubDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=3000)),
                ('belongToBoard', models.IntegerField()),
                ('belongToComment', models.IntegerField()),
                ('stance', models.IntegerField()),
                ('reportStatus', models.CharField(max_length=10)),
                ('noticeChecked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonimity', models.BooleanField(default=False)),
                ('annoName', models.CharField(max_length=20)),
                ('isWriter', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('vote', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
                ('pubDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('hitCount', models.IntegerField()),
                ('boardNum', models.IntegerField()),
                ('reportStatus', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('boardType', models.CharField(blank=True, max_length=10)),
                ('itemType', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonimity', models.BooleanField(default=False)),
                ('annoName', models.CharField(max_length=20)),
                ('isWriter', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('vote', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.Post')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickName', models.CharField(max_length=20)),
                ('studentId', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('birthDate', models.DateField()),
                ('signInDate', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(upload_to='')),
                ('phone', models.CharField(default=None, max_length=15)),
                ('resign', models.BooleanField(default=False)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='postrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(through='heart.PostRelation', to='heart.User'),
        ),
        migrations.AddField(
            model_name='file',
            name='belongTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.Post'),
        ),
        migrations.AddField(
            model_name='comrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ManyToManyField(through='heart.ComRelation', to='heart.User'),
        ),
    ]
