# Generated by Django 2.1.3 on 2019-01-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_auto_20190118_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hitCount',
            field=models.IntegerField(default=0),
        ),
    ]
