# Generated by Django 2.1.3 on 2019-01-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_auto_20190118_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrelation',
            name='vote',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='postrelation',
            name='vote',
            field=models.IntegerField(default=-1),
        ),
    ]
