# Generated by Django 2.1.3 on 2019-01-21 13:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_auto_20190118_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentEditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postEditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belongToBoard',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belongToComment',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stance',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comrelation',
            name='vote',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='boardNum',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='hitCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postrelation',
            name='vote',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentId',
            field=models.PositiveIntegerField(),
        ),
    ]
