# Generated by Django 2.1.3 on 2019-01-21 13:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_auto_20190121_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentEditor',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentEditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
