# Generated by Django 2.1.3 on 2019-01-22 06:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0007_auto_20190121_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postEditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
